import type { Metadata, Viewport } from "next";
import { SessionProvider } from "next-auth/react";
import "@fontsource/space-grotesk/700.css";
import "./globals.css";

const SITE_URL = "https://oralab.xyz";
const SITE_NAME = "oralab";
// SERP guidelines: lead with the keyword phrase, brand at the end
// after a pipe. Single dash inside the keyword phrase reads better
// than two-or-three "·" separators which look noisy in Google's
// rendered title.
const SITE_TITLE = "Polymarket whale tracker — live PnL heatmap | oralab";
// Target ~150-160 chars before Google truncates. Single sentence,
// load-bearing nouns at the front, no internal-jargon ("PATTERN
// view", "dossier") that reads like marketing fluff in a snippet.
const SITE_DESCRIPTION =
  "Real-time heatmap of every Polymarket trade from 10,000+ top wallets. Drill into hot markets and see which whales are pushing them — across 9 categories.";

export const metadata: Metadata = {
  // metadataBase resolves all relative og:image / twitter:image URLs
  // against this origin so the social-preview links don't 404 in
  // Slack / X / Discord crawlers.
  metadataBase: new URL(SITE_URL),
  title: {
    // Each page sets its own title via `title.absolute` or via a slot;
    // anything else falls back to the default.
    template: `%s · ${SITE_NAME}`,
    default: SITE_TITLE,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  // Concrete keyword set the landing should rank for. Modern Google
  // mostly ignores meta-keywords but Bing/Yandex/DuckDuckGo still
  // use it as a weak signal.
  keywords: [
    "polymarket",
    "polymarket whale tracker",
    "polymarket smart money",
    "polymarket signals",
    "polymarket dashboard",
    "polymarket pnl",
    "polymarket leaderboard",
    "prediction market whales",
    "smart money tracker",
    "onchain whale tracking",
    "real-time whale alerts",
  ],
  icons: {
    // Order matters — browsers / crawlers pick the first format they
    // support. SVG first for crisp browser tabs at any DPR; the PNG
    // generated by app/icon.tsx is the fallback Google's SERP pipeline
    // actually reads (SVG support there is patchy and we showed up as
    // the generic globe in search results).
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/icon", sizes: "32x32", type: "image/png" },
    ],
    apple: [{ url: "/apple-icon", sizes: "180x180", type: "image/png" }],
  },
  alternates: { canonical: SITE_URL },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    url: SITE_URL,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    // Account that owns the site / created the content. When someone
    // tweets a link to oralab.xyz the card surfaces "via @oralabxyz".
    site: "@oralabxyz",
    creator: "@oralabxyz",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  // Search-engine site-ownership tokens. Each key writes a single
  // <meta> in the document head; the engines read it once on
  // verification and never look at it again.
  verification: {
    other: {
      "msvalidate.01": "A893533E8252BFC576390F470266C4F3",
    },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0d1117",
  // viewport-fit=cover enables env(safe-area-inset-*) on iOS Safari so
  // the header can clear the notch / status bar on iPhone X-class devices
  // and the StatsBar can clear the home-indicator on iOS.
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
